### ISSUE TITLE
Log scales

### ISSUE THREAD

**Issue by sebastian-gerdes** [kjhealy/england_gdp_long#1]
Hello!

I really like the plots!

I fiddled around a bit with the code. In my opinion the figures would be a lot more informative if presented on log scale!

What do you think?

Best greetings,
Sebastian

![image](https://user-images.githubusercontent.com/61906380/227868361-2ef9ee60-8586-425c-8151-a42de5bcd24e.png)

**Comment by kjhealy** [comment]
The animations are intended to convey the extreme change in magnitudes over time in both population and GDP per capita, so linear axes work well. But of course log scales are good too, especially for a single view like this.
